[tool.poetry]
name = "pymgogm"
version = "0.1.0"
description = "Memgraph dsl library"
authors = [
    "Matko Budiselic <marko.budiselic@memgraph.io>",
    "Jure Bajic <jure.bajic@memgraph.io>",
    "Josip Mrden <josip.mrden@memgraph.io>",
    "Josip Matak <josip.matak@memgraph.io>",
]
license = "Apache-2.0"

[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^6.2.4"
pymgclient = "^1.0.0"

[tool.poetry.dev-dependencies]
black = "^21.5b1"
pytest-black = "^0.3.12"
pytest-flake8 = "^1.0.7"
pytest-mypy = "^0.8.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
