name: Build and Test

env:
  MG_VERSION: '1.4.0'
  PY_VERSION: '3.8'
  POETRY_VERSION: '1.1.4'

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ env.PY_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PY_VERSION }}
    - name: Setup poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: ${{ env.POETRY_VERSION }}

    - name: Run memgraph instance
      run: |
        docker run -d -p 7687:7687 memgraph/memgraph --telemetry-enabled=False
    - name: Test project
      run: |
        poetry install
        poetry run pytest -vvv -m "not slow"
